//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary_sjb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vsystem_sjbEntities : DbContext
    {
        public vsystem_sjbEntities()
            : base("name=vsystem_sjbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_departamento> tbl_departamento { get; set; }
        public DbSet<tbl_estatus> tbl_estatus { get; set; }
        public DbSet<tbl_jerarquia> tbl_jerarquia { get; set; }
        public DbSet<tbl_log_vacaciones> tbl_log_vacaciones { get; set; }
        public DbSet<tbl_permisos> tbl_permisos { get; set; }
        public DbSet<tbl_roles> tbl_roles { get; set; }
        public DbSet<tbl_usuarios> tbl_usuarios { get; set; }
        public DbSet<tbl_vacaciones> tbl_vacaciones { get; set; }
        public DbSet<tbl_tipo_dia> tbl_tipo_dia { get; set; }
        public DbSet<tbl_calendario> tbl_calendario { get; set; }
    }
}
