//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary_sjb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vacaciones
    {
        public tbl_vacaciones()
        {
            this.tbl_log_vacaciones = new HashSet<tbl_log_vacaciones>();
        }
    
        public int vacacionesid { get; set; }
        public int talento_humano { get; set; }
        public int year { get; set; }
        public System.DateTime fecha_salida { get; set; }
        public System.DateTime fecha_entrada { get; set; }
        public int dias_solicitados { get; set; }
        public int fecha_solicitud { get; set; }
        public System.DateTime fecha_de_aprobacion { get; set; }
        public int estatusid { get; set; }
    
        public virtual tbl_estatus tbl_estatus { get; set; }
        public virtual ICollection<tbl_log_vacaciones> tbl_log_vacaciones { get; set; }
        public virtual tbl_usuarios tbl_usuarios { get; set; }
    }
}
