//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary_sjb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_departamento
    {
        public tbl_departamento()
        {
            this.tbl_jerarquia = new HashSet<tbl_jerarquia>();
            this.tbl_usuarios = new HashSet<tbl_usuarios>();
        }
    
        public int departamentoid { get; set; }
        public string descripcion { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<tbl_jerarquia> tbl_jerarquia { get; set; }
        public virtual ICollection<tbl_usuarios> tbl_usuarios { get; set; }
    }
}
