//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary_sjb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_roles
    {
        public tbl_roles()
        {
            this.tbl_permisos = new HashSet<tbl_permisos>();
            this.tbl_usuarios = new HashSet<tbl_usuarios>();
        }
    
        public int rolesid { get; set; }
        public string descripcion { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<tbl_permisos> tbl_permisos { get; set; }
        public virtual ICollection<tbl_usuarios> tbl_usuarios { get; set; }
    }
}
