//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVacacionesUnitec.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_sjb")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_sjb")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        GestionVacacionesUnitec.ServiceReference1.CompositeType GetDataUsingDataContract(GestionVacacionesUnitec.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<GestionVacacionesUnitec.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(GestionVacacionesUnitec.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregarUsuario", ReplyAction="http://tempuri.org/IService1/agregarUsuarioResponse")]
        void agregarUsuario(string talentoH, string correo, string password, string nombre1, string nombre2, string apellido1, string apellido2, string fechaIngreso, string fechaCreacion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregarUsuario", ReplyAction="http://tempuri.org/IService1/agregarUsuarioResponse")]
        System.Threading.Tasks.Task agregarUsuarioAsync(string talentoH, string correo, string password, string nombre1, string nombre2, string apellido1, string apellido2, string fechaIngreso, string fechaCreacion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LogInUsuario", ReplyAction="http://tempuri.org/IService1/LogInUsuarioResponse")]
        GestionVacacionesUnitec.ServiceReference1.Usuario LogInUsuario(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LogInUsuario", ReplyAction="http://tempuri.org/IService1/LogInUsuarioResponse")]
        System.Threading.Tasks.Task<GestionVacacionesUnitec.ServiceReference1.Usuario> LogInUsuarioAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregarDepartamento", ReplyAction="http://tempuri.org/IService1/agregarDepartamentoResponse")]
        void agregarDepartamento(string ID, string descripcion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregarDepartamento", ReplyAction="http://tempuri.org/IService1/agregarDepartamentoResponse")]
        System.Threading.Tasks.Task agregarDepartamentoAsync(string ID, string descripcion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregarRol", ReplyAction="http://tempuri.org/IService1/agregarRolResponse")]
        void agregarRol(string ID, string descripcion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregarRol", ReplyAction="http://tempuri.org/IService1/agregarRolResponse")]
        System.Threading.Tasks.Task agregarRolAsync(string ID, string descripcion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Rol_Usuario", ReplyAction="http://tempuri.org/IService1/Rol_UsuarioResponse")]
        void Rol_Usuario(string ID_rol, string ID_permiso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Rol_Usuario", ReplyAction="http://tempuri.org/IService1/Rol_UsuarioResponse")]
        System.Threading.Tasks.Task Rol_UsuarioAsync(string ID_rol, string ID_permiso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Usuario_Departamento", ReplyAction="http://tempuri.org/IService1/Usuario_DepartamentoResponse")]
        void Usuario_Departamento(string Talento_Humano, string ID_departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Usuario_Departamento", ReplyAction="http://tempuri.org/IService1/Usuario_DepartamentoResponse")]
        System.Threading.Tasks.Task Usuario_DepartamentoAsync(string Talento_Humano, string ID_departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Usuario_Rol", ReplyAction="http://tempuri.org/IService1/Usuario_RolResponse")]
        void Usuario_Rol(string Talento_Humano, string ID_rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Usuario_Rol", ReplyAction="http://tempuri.org/IService1/Usuario_RolResponse")]
        System.Threading.Tasks.Task Usuario_RolAsync(string Talento_Humano, string ID_rol);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : GestionVacacionesUnitec.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<GestionVacacionesUnitec.ServiceReference1.IService1>, GestionVacacionesUnitec.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public GestionVacacionesUnitec.ServiceReference1.CompositeType GetDataUsingDataContract(GestionVacacionesUnitec.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<GestionVacacionesUnitec.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(GestionVacacionesUnitec.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public void agregarUsuario(string talentoH, string correo, string password, string nombre1, string nombre2, string apellido1, string apellido2, string fechaIngreso, string fechaCreacion, bool activo) {
            base.Channel.agregarUsuario(talentoH, correo, password, nombre1, nombre2, apellido1, apellido2, fechaIngreso, fechaCreacion, activo);
        }
        
        public System.Threading.Tasks.Task agregarUsuarioAsync(string talentoH, string correo, string password, string nombre1, string nombre2, string apellido1, string apellido2, string fechaIngreso, string fechaCreacion, bool activo) {
            return base.Channel.agregarUsuarioAsync(talentoH, correo, password, nombre1, nombre2, apellido1, apellido2, fechaIngreso, fechaCreacion, activo);
        }
        
        public GestionVacacionesUnitec.ServiceReference1.Usuario LogInUsuario(string email, string password) {
            return base.Channel.LogInUsuario(email, password);
        }
        
        public System.Threading.Tasks.Task<GestionVacacionesUnitec.ServiceReference1.Usuario> LogInUsuarioAsync(string email, string password) {
            return base.Channel.LogInUsuarioAsync(email, password);
        }
        
        public void agregarDepartamento(string ID, string descripcion, bool activo) {
            base.Channel.agregarDepartamento(ID, descripcion, activo);
        }
        
        public System.Threading.Tasks.Task agregarDepartamentoAsync(string ID, string descripcion, bool activo) {
            return base.Channel.agregarDepartamentoAsync(ID, descripcion, activo);
        }
        
        public void agregarRol(string ID, string descripcion, bool activo) {
            base.Channel.agregarRol(ID, descripcion, activo);
        }
        
        public System.Threading.Tasks.Task agregarRolAsync(string ID, string descripcion, bool activo) {
            return base.Channel.agregarRolAsync(ID, descripcion, activo);
        }
        
        public void Rol_Usuario(string ID_rol, string ID_permiso) {
            base.Channel.Rol_Usuario(ID_rol, ID_permiso);
        }
        
        public System.Threading.Tasks.Task Rol_UsuarioAsync(string ID_rol, string ID_permiso) {
            return base.Channel.Rol_UsuarioAsync(ID_rol, ID_permiso);
        }
        
        public void Usuario_Departamento(string Talento_Humano, string ID_departamento) {
            base.Channel.Usuario_Departamento(Talento_Humano, ID_departamento);
        }
        
        public System.Threading.Tasks.Task Usuario_DepartamentoAsync(string Talento_Humano, string ID_departamento) {
            return base.Channel.Usuario_DepartamentoAsync(Talento_Humano, ID_departamento);
        }
        
        public void Usuario_Rol(string Talento_Humano, string ID_rol) {
            base.Channel.Usuario_Rol(Talento_Humano, ID_rol);
        }
        
        public System.Threading.Tasks.Task Usuario_RolAsync(string Talento_Humano, string ID_rol) {
            return base.Channel.Usuario_RolAsync(Talento_Humano, ID_rol);
        }
    }
}
