//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVacacionesUnitec.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_sjb")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_sjb")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_CreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_IngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Primer_ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Primer_NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Segundo_ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Segundo_NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Talento_HumanoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Creacion {
            get {
                return this.Fecha_CreacionField;
            }
            set {
                if ((this.Fecha_CreacionField.Equals(value) != true)) {
                    this.Fecha_CreacionField = value;
                    this.RaisePropertyChanged("Fecha_Creacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Ingreso {
            get {
                return this.Fecha_IngresoField;
            }
            set {
                if ((this.Fecha_IngresoField.Equals(value) != true)) {
                    this.Fecha_IngresoField = value;
                    this.RaisePropertyChanged("Fecha_Ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Primer_Apellido {
            get {
                return this.Primer_ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.Primer_ApellidoField, value) != true)) {
                    this.Primer_ApellidoField = value;
                    this.RaisePropertyChanged("Primer_Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Primer_Nombre {
            get {
                return this.Primer_NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.Primer_NombreField, value) != true)) {
                    this.Primer_NombreField = value;
                    this.RaisePropertyChanged("Primer_Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Segundo_Apellido {
            get {
                return this.Segundo_ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.Segundo_ApellidoField, value) != true)) {
                    this.Segundo_ApellidoField = value;
                    this.RaisePropertyChanged("Segundo_Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Segundo_Nombre {
            get {
                return this.Segundo_NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.Segundo_NombreField, value) != true)) {
                    this.Segundo_NombreField = value;
                    this.RaisePropertyChanged("Segundo_Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Talento_Humano {
            get {
                return this.Talento_HumanoField;
            }
            set {
                if ((this.Talento_HumanoField.Equals(value) != true)) {
                    this.Talento_HumanoField = value;
                    this.RaisePropertyChanged("Talento_Humano");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_usuarios", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_sjb")]
    [System.SerializableAttribute()]
    public partial class tbl_usuarios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_creacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_ingresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primer_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primer_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int talento_humanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_calendario[] tbl_calendarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_calendario[] tbl_calendario1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_departamento[] tbl_departamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_jerarquia[] tbl_jerarquiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_jerarquia[] tbl_jerarquia1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_log_vacaciones[] tbl_log_vacacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_roles[] tbl_rolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_vacaciones[] tbl_vacacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_creacion {
            get {
                return this.fecha_creacionField;
            }
            set {
                if ((this.fecha_creacionField.Equals(value) != true)) {
                    this.fecha_creacionField = value;
                    this.RaisePropertyChanged("fecha_creacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_ingreso {
            get {
                return this.fecha_ingresoField;
            }
            set {
                if ((this.fecha_ingresoField.Equals(value) != true)) {
                    this.fecha_ingresoField = value;
                    this.RaisePropertyChanged("fecha_ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primer_apellido {
            get {
                return this.primer_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primer_apellidoField, value) != true)) {
                    this.primer_apellidoField = value;
                    this.RaisePropertyChanged("primer_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primer_nombre {
            get {
                return this.primer_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.primer_nombreField, value) != true)) {
                    this.primer_nombreField = value;
                    this.RaisePropertyChanged("primer_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundo_apellido {
            get {
                return this.segundo_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_apellidoField, value) != true)) {
                    this.segundo_apellidoField = value;
                    this.RaisePropertyChanged("segundo_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundo_nombre {
            get {
                return this.segundo_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_nombreField, value) != true)) {
                    this.segundo_nombreField = value;
                    this.RaisePropertyChanged("segundo_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int talento_humano {
            get {
                return this.talento_humanoField;
            }
            set {
                if ((this.talento_humanoField.Equals(value) != true)) {
                    this.talento_humanoField = value;
                    this.RaisePropertyChanged("talento_humano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_calendario[] tbl_calendario {
            get {
                return this.tbl_calendarioField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_calendarioField, value) != true)) {
                    this.tbl_calendarioField = value;
                    this.RaisePropertyChanged("tbl_calendario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_calendario[] tbl_calendario1 {
            get {
                return this.tbl_calendario1Field;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_calendario1Field, value) != true)) {
                    this.tbl_calendario1Field = value;
                    this.RaisePropertyChanged("tbl_calendario1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_departamento[] tbl_departamento {
            get {
                return this.tbl_departamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_departamentoField, value) != true)) {
                    this.tbl_departamentoField = value;
                    this.RaisePropertyChanged("tbl_departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_jerarquia[] tbl_jerarquia {
            get {
                return this.tbl_jerarquiaField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_jerarquiaField, value) != true)) {
                    this.tbl_jerarquiaField = value;
                    this.RaisePropertyChanged("tbl_jerarquia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_jerarquia[] tbl_jerarquia1 {
            get {
                return this.tbl_jerarquia1Field;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_jerarquia1Field, value) != true)) {
                    this.tbl_jerarquia1Field = value;
                    this.RaisePropertyChanged("tbl_jerarquia1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_log_vacaciones[] tbl_log_vacaciones {
            get {
                return this.tbl_log_vacacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_log_vacacionesField, value) != true)) {
                    this.tbl_log_vacacionesField = value;
                    this.RaisePropertyChanged("tbl_log_vacaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_roles[] tbl_roles {
            get {
                return this.tbl_rolesField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_rolesField, value) != true)) {
                    this.tbl_rolesField = value;
                    this.RaisePropertyChanged("tbl_roles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_vacaciones[] tbl_vacaciones {
            get {
                return this.tbl_vacacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_vacacionesField, value) != true)) {
                    this.tbl_vacacionesField = value;
                    this.RaisePropertyChanged("tbl_vacaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_calendario", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_sjb")]
    [System.SerializableAttribute()]
    public partial class tbl_calendario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int talento_humano_empleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int talento_humano_jefeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_tipo_dia tbl_tipo_diaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_usuarios tbl_usuariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_usuarios tbl_usuarios1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tipo_dia_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int talento_humano_empleado {
            get {
                return this.talento_humano_empleadoField;
            }
            set {
                if ((this.talento_humano_empleadoField.Equals(value) != true)) {
                    this.talento_humano_empleadoField = value;
                    this.RaisePropertyChanged("talento_humano_empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int talento_humano_jefe {
            get {
                return this.talento_humano_jefeField;
            }
            set {
                if ((this.talento_humano_jefeField.Equals(value) != true)) {
                    this.talento_humano_jefeField = value;
                    this.RaisePropertyChanged("talento_humano_jefe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_tipo_dia tbl_tipo_dia {
            get {
                return this.tbl_tipo_diaField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_tipo_diaField, value) != true)) {
                    this.tbl_tipo_diaField = value;
                    this.RaisePropertyChanged("tbl_tipo_dia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_usuarios tbl_usuarios {
            get {
                return this.tbl_usuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_usuariosField, value) != true)) {
                    this.tbl_usuariosField = value;
                    this.RaisePropertyChanged("tbl_usuarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_usuarios tbl_usuarios1 {
            get {
                return this.tbl_usuarios1Field;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_usuarios1Field, value) != true)) {
                    this.tbl_usuarios1Field = value;
                    this.RaisePropertyChanged("tbl_usuarios1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tipo_dia_id {
            get {
                return this.tipo_dia_idField;
            }
            set {
                if ((this.tipo_dia_idField.Equals(value) != true)) {
                    this.tipo_dia_idField = value;
                    this.RaisePropertyChanged("tipo_dia_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_departamento", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_sjb")]
    [System.SerializableAttribute()]
    public partial class tbl_departamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int departamentoidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_jerarquia[] tbl_jerarquiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_usuarios[] tbl_usuariosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int departamentoid {
            get {
                return this.departamentoidField;
            }
            set {
                if ((this.departamentoidField.Equals(value) != true)) {
                    this.departamentoidField = value;
                    this.RaisePropertyChanged("departamentoid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_jerarquia[] tbl_jerarquia {
            get {
                return this.tbl_jerarquiaField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_jerarquiaField, value) != true)) {
                    this.tbl_jerarquiaField = value;
                    this.RaisePropertyChanged("tbl_jerarquia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_usuarios[] tbl_usuarios {
            get {
                return this.tbl_usuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_usuariosField, value) != true)) {
                    this.tbl_usuariosField = value;
                    this.RaisePropertyChanged("tbl_usuarios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_jerarquia", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_sjb")]
    [System.SerializableAttribute()]
    public partial class tbl_jerarquia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int departamentoidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jefe_talentohumanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jerarquiaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int talento_humanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_departamento tbl_departamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_usuarios tbl_usuariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_usuarios tbl_usuarios1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int departamentoid {
            get {
                return this.departamentoidField;
            }
            set {
                if ((this.departamentoidField.Equals(value) != true)) {
                    this.departamentoidField = value;
                    this.RaisePropertyChanged("departamentoid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jefe_talentohumano {
            get {
                return this.jefe_talentohumanoField;
            }
            set {
                if ((this.jefe_talentohumanoField.Equals(value) != true)) {
                    this.jefe_talentohumanoField = value;
                    this.RaisePropertyChanged("jefe_talentohumano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jerarquiaid {
            get {
                return this.jerarquiaidField;
            }
            set {
                if ((this.jerarquiaidField.Equals(value) != true)) {
                    this.jerarquiaidField = value;
                    this.RaisePropertyChanged("jerarquiaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int talento_humano {
            get {
                return this.talento_humanoField;
            }
            set {
                if ((this.talento_humanoField.Equals(value) != true)) {
                    this.talento_humanoField = value;
                    this.RaisePropertyChanged("talento_humano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_departamento tbl_departamento {
            get {
                return this.tbl_departamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_departamentoField, value) != true)) {
                    this.tbl_departamentoField = value;
                    this.RaisePropertyChanged("tbl_departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_usuarios tbl_usuarios {
            get {
                return this.tbl_usuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_usuariosField, value) != true)) {
                    this.tbl_usuariosField = value;
                    this.RaisePropertyChanged("tbl_usuarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_usuarios tbl_usuarios1 {
            get {
                return this.tbl_usuarios1Field;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_usuarios1Field, value) != true)) {
                    this.tbl_usuarios1Field = value;
                    this.RaisePropertyChanged("tbl_usuarios1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_log_vacaciones", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_sjb")]
    [System.SerializableAttribute()]
    public partial class tbl_log_vacaciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estatus_actualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> estatus_anteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_modificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int logidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_estatus tbl_estatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_estatus tbl_estatus1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_usuarios tbl_usuariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_vacaciones tbl_vacacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int th_modificoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int vacacionesidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estatus_actual {
            get {
                return this.estatus_actualField;
            }
            set {
                if ((this.estatus_actualField.Equals(value) != true)) {
                    this.estatus_actualField = value;
                    this.RaisePropertyChanged("estatus_actual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> estatus_anterior {
            get {
                return this.estatus_anteriorField;
            }
            set {
                if ((this.estatus_anteriorField.Equals(value) != true)) {
                    this.estatus_anteriorField = value;
                    this.RaisePropertyChanged("estatus_anterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_modificacion {
            get {
                return this.fecha_modificacionField;
            }
            set {
                if ((this.fecha_modificacionField.Equals(value) != true)) {
                    this.fecha_modificacionField = value;
                    this.RaisePropertyChanged("fecha_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int logid {
            get {
                return this.logidField;
            }
            set {
                if ((this.logidField.Equals(value) != true)) {
                    this.logidField = value;
                    this.RaisePropertyChanged("logid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_estatus tbl_estatus {
            get {
                return this.tbl_estatusField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_estatusField, value) != true)) {
                    this.tbl_estatusField = value;
                    this.RaisePropertyChanged("tbl_estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_estatus tbl_estatus1 {
            get {
                return this.tbl_estatus1Field;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_estatus1Field, value) != true)) {
                    this.tbl_estatus1Field = value;
                    this.RaisePropertyChanged("tbl_estatus1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_usuarios tbl_usuarios {
            get {
                return this.tbl_usuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_usuariosField, value) != true)) {
                    this.tbl_usuariosField = value;
                    this.RaisePropertyChanged("tbl_usuarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_vacaciones tbl_vacaciones {
            get {
                return this.tbl_vacacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_vacacionesField, value) != true)) {
                    this.tbl_vacacionesField = value;
                    this.RaisePropertyChanged("tbl_vacaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int th_modifico {
            get {
                return this.th_modificoField;
            }
            set {
                if ((this.th_modificoField.Equals(value) != true)) {
                    this.th_modificoField = value;
                    this.RaisePropertyChanged("th_modifico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int vacacionesid {
            get {
                return this.vacacionesidField;
            }
            set {
                if ((this.vacacionesidField.Equals(value) != true)) {
                    this.vacacionesidField = value;
                    this.RaisePropertyChanged("vacacionesid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_roles", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_sjb")]
    [System.SerializableAttribute()]
    public partial class tbl_roles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rolesidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_permisos[] tbl_permisosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_usuarios[] tbl_usuariosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rolesid {
            get {
                return this.rolesidField;
            }
            set {
                if ((this.rolesidField.Equals(value) != true)) {
                    this.rolesidField = value;
                    this.RaisePropertyChanged("rolesid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_permisos[] tbl_permisos {
            get {
                return this.tbl_permisosField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_permisosField, value) != true)) {
                    this.tbl_permisosField = value;
                    this.RaisePropertyChanged("tbl_permisos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_usuarios[] tbl_usuarios {
            get {
                return this.tbl_usuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_usuariosField, value) != true)) {
                    this.tbl_usuariosField = value;
                    this.RaisePropertyChanged("tbl_usuarios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_vacaciones", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_sjb")]
    [System.SerializableAttribute()]
    public partial class tbl_vacaciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int dias_solicitadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estatusidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_de_aprobacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_entradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_salidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fecha_solicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int talento_humanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_estatus tbl_estatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_log_vacaciones[] tbl_log_vacacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_usuarios tbl_usuariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int vacacionesidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int dias_solicitados {
            get {
                return this.dias_solicitadosField;
            }
            set {
                if ((this.dias_solicitadosField.Equals(value) != true)) {
                    this.dias_solicitadosField = value;
                    this.RaisePropertyChanged("dias_solicitados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estatusid {
            get {
                return this.estatusidField;
            }
            set {
                if ((this.estatusidField.Equals(value) != true)) {
                    this.estatusidField = value;
                    this.RaisePropertyChanged("estatusid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_de_aprobacion {
            get {
                return this.fecha_de_aprobacionField;
            }
            set {
                if ((this.fecha_de_aprobacionField.Equals(value) != true)) {
                    this.fecha_de_aprobacionField = value;
                    this.RaisePropertyChanged("fecha_de_aprobacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_entrada {
            get {
                return this.fecha_entradaField;
            }
            set {
                if ((this.fecha_entradaField.Equals(value) != true)) {
                    this.fecha_entradaField = value;
                    this.RaisePropertyChanged("fecha_entrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_salida {
            get {
                return this.fecha_salidaField;
            }
            set {
                if ((this.fecha_salidaField.Equals(value) != true)) {
                    this.fecha_salidaField = value;
                    this.RaisePropertyChanged("fecha_salida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fecha_solicitud {
            get {
                return this.fecha_solicitudField;
            }
            set {
                if ((this.fecha_solicitudField.Equals(value) != true)) {
                    this.fecha_solicitudField = value;
                    this.RaisePropertyChanged("fecha_solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int talento_humano {
            get {
                return this.talento_humanoField;
            }
            set {
                if ((this.talento_humanoField.Equals(value) != true)) {
                    this.talento_humanoField = value;
                    this.RaisePropertyChanged("talento_humano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_estatus tbl_estatus {
            get {
                return this.tbl_estatusField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_estatusField, value) != true)) {
                    this.tbl_estatusField = value;
                    this.RaisePropertyChanged("tbl_estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_log_vacaciones[] tbl_log_vacaciones {
            get {
                return this.tbl_log_vacacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_log_vacacionesField, value) != true)) {
                    this.tbl_log_vacacionesField = value;
                    this.RaisePropertyChanged("tbl_log_vacaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_usuarios tbl_usuarios {
            get {
                return this.tbl_usuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_usuariosField, value) != true)) {
                    this.tbl_usuariosField = value;
                    this.RaisePropertyChanged("tbl_usuarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int vacacionesid {
            get {
                return this.vacacionesidField;
            }
            set {
                if ((this.vacacionesidField.Equals(value) != true)) {
                    this.vacacionesidField = value;
                    this.RaisePropertyChanged("vacacionesid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int year {
            get {
                return this.yearField;
            }
            set {
                if ((this.yearField.Equals(value) != true)) {
                    this.yearField = value;
                    this.RaisePropertyChanged("year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_tipo_dia", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_sjb")]
    [System.SerializableAttribute()]
    public partial class tbl_tipo_dia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_calendario[] tbl_calendarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tipo_dia_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((this.descripcionField.Equals(value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_calendario[] tbl_calendario {
            get {
                return this.tbl_calendarioField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_calendarioField, value) != true)) {
                    this.tbl_calendarioField = value;
                    this.RaisePropertyChanged("tbl_calendario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tipo_dia_id {
            get {
                return this.tipo_dia_idField;
            }
            set {
                if ((this.tipo_dia_idField.Equals(value) != true)) {
                    this.tipo_dia_idField = value;
                    this.RaisePropertyChanged("tipo_dia_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_estatus", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_sjb")]
    [System.SerializableAttribute()]
    public partial class tbl_estatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estatusidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_log_vacaciones[] tbl_log_vacacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_log_vacaciones[] tbl_log_vacaciones1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_vacaciones[] tbl_vacacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estatusid {
            get {
                return this.estatusidField;
            }
            set {
                if ((this.estatusidField.Equals(value) != true)) {
                    this.estatusidField = value;
                    this.RaisePropertyChanged("estatusid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_log_vacaciones[] tbl_log_vacaciones {
            get {
                return this.tbl_log_vacacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_log_vacacionesField, value) != true)) {
                    this.tbl_log_vacacionesField = value;
                    this.RaisePropertyChanged("tbl_log_vacaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_log_vacaciones[] tbl_log_vacaciones1 {
            get {
                return this.tbl_log_vacaciones1Field;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_log_vacaciones1Field, value) != true)) {
                    this.tbl_log_vacaciones1Field = value;
                    this.RaisePropertyChanged("tbl_log_vacaciones1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_vacaciones[] tbl_vacaciones {
            get {
                return this.tbl_vacacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_vacacionesField, value) != true)) {
                    this.tbl_vacacionesField = value;
                    this.RaisePropertyChanged("tbl_vacaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_permisos", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_sjb")]
    [System.SerializableAttribute()]
    public partial class tbl_permisos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int permisosidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionVacacionesUnitec.ServiceReference1.tbl_roles[] tbl_rolesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int permisosid {
            get {
                return this.permisosidField;
            }
            set {
                if ((this.permisosidField.Equals(value) != true)) {
                    this.permisosidField = value;
                    this.RaisePropertyChanged("permisosid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionVacacionesUnitec.ServiceReference1.tbl_roles[] tbl_roles {
            get {
                return this.tbl_rolesField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_rolesField, value) != true)) {
                    this.tbl_rolesField = value;
                    this.RaisePropertyChanged("tbl_roles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        GestionVacacionesUnitec.ServiceReference1.CompositeType GetDataUsingDataContract(GestionVacacionesUnitec.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<GestionVacacionesUnitec.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(GestionVacacionesUnitec.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregarUsuario", ReplyAction="http://tempuri.org/IService1/agregarUsuarioResponse")]
        void agregarUsuario(string talentoH, string correo, string password, string nombre1, string nombre2, string apellido1, string apellido2, string fechaIngreso, string fechaCreacion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregarUsuario", ReplyAction="http://tempuri.org/IService1/agregarUsuarioResponse")]
        System.Threading.Tasks.Task agregarUsuarioAsync(string talentoH, string correo, string password, string nombre1, string nombre2, string apellido1, string apellido2, string fechaIngreso, string fechaCreacion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LogInUsuario", ReplyAction="http://tempuri.org/IService1/LogInUsuarioResponse")]
        GestionVacacionesUnitec.ServiceReference1.Usuario LogInUsuario(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LogInUsuario", ReplyAction="http://tempuri.org/IService1/LogInUsuarioResponse")]
        System.Threading.Tasks.Task<GestionVacacionesUnitec.ServiceReference1.Usuario> LogInUsuarioAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LogIn2", ReplyAction="http://tempuri.org/IService1/LogIn2Response")]
        int LogIn2(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LogIn2", ReplyAction="http://tempuri.org/IService1/LogIn2Response")]
        System.Threading.Tasks.Task<int> LogIn2Async(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregarDepartamento", ReplyAction="http://tempuri.org/IService1/agregarDepartamentoResponse")]
        void agregarDepartamento(string ID, string descripcion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregarDepartamento", ReplyAction="http://tempuri.org/IService1/agregarDepartamentoResponse")]
        System.Threading.Tasks.Task agregarDepartamentoAsync(string ID, string descripcion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregarRol", ReplyAction="http://tempuri.org/IService1/agregarRolResponse")]
        void agregarRol(string ID, string descripcion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregarRol", ReplyAction="http://tempuri.org/IService1/agregarRolResponse")]
        System.Threading.Tasks.Task agregarRolAsync(string ID, string descripcion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Rol_Permiso", ReplyAction="http://tempuri.org/IService1/Rol_PermisoResponse")]
        void Rol_Permiso(string ID_rol, string ID_permiso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Rol_Permiso", ReplyAction="http://tempuri.org/IService1/Rol_PermisoResponse")]
        System.Threading.Tasks.Task Rol_PermisoAsync(string ID_rol, string ID_permiso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Usuario_Departamento", ReplyAction="http://tempuri.org/IService1/Usuario_DepartamentoResponse")]
        void Usuario_Departamento(string Talento_Humano, string descripcion_departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Usuario_Departamento", ReplyAction="http://tempuri.org/IService1/Usuario_DepartamentoResponse")]
        System.Threading.Tasks.Task Usuario_DepartamentoAsync(string Talento_Humano, string descripcion_departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Usuario_Rol", ReplyAction="http://tempuri.org/IService1/Usuario_RolResponse")]
        void Usuario_Rol(string Talento_Humano, string descripcion_rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Usuario_Rol", ReplyAction="http://tempuri.org/IService1/Usuario_RolResponse")]
        System.Threading.Tasks.Task Usuario_RolAsync(string Talento_Humano, string descripcion_rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LogInUsuario2", ReplyAction="http://tempuri.org/IService1/LogInUsuario2Response")]
        GestionVacacionesUnitec.ServiceReference1.tbl_usuarios LogInUsuario2(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LogInUsuario2", ReplyAction="http://tempuri.org/IService1/LogInUsuario2Response")]
        System.Threading.Tasks.Task<GestionVacacionesUnitec.ServiceReference1.tbl_usuarios> LogInUsuario2Async(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaDeDepartamentos", ReplyAction="http://tempuri.org/IService1/ListaDeDepartamentosResponse")]
        GestionVacacionesUnitec.ServiceReference1.tbl_departamento[] ListaDeDepartamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaDeDepartamentos", ReplyAction="http://tempuri.org/IService1/ListaDeDepartamentosResponse")]
        System.Threading.Tasks.Task<GestionVacacionesUnitec.ServiceReference1.tbl_departamento[]> ListaDeDepartamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaDeRoles", ReplyAction="http://tempuri.org/IService1/ListaDeRolesResponse")]
        GestionVacacionesUnitec.ServiceReference1.tbl_roles[] ListaDeRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaDeRoles", ReplyAction="http://tempuri.org/IService1/ListaDeRolesResponse")]
        System.Threading.Tasks.Task<GestionVacacionesUnitec.ServiceReference1.tbl_roles[]> ListaDeRolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaDeRolesPorUsuario", ReplyAction="http://tempuri.org/IService1/ListaDeRolesPorUsuarioResponse")]
        GestionVacacionesUnitec.ServiceReference1.tbl_roles ListaDeRolesPorUsuario(string talento_humano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaDeRolesPorUsuario", ReplyAction="http://tempuri.org/IService1/ListaDeRolesPorUsuarioResponse")]
        System.Threading.Tasks.Task<GestionVacacionesUnitec.ServiceReference1.tbl_roles> ListaDeRolesPorUsuarioAsync(string talento_humano);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : GestionVacacionesUnitec.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<GestionVacacionesUnitec.ServiceReference1.IService1>, GestionVacacionesUnitec.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public GestionVacacionesUnitec.ServiceReference1.CompositeType GetDataUsingDataContract(GestionVacacionesUnitec.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<GestionVacacionesUnitec.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(GestionVacacionesUnitec.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public void agregarUsuario(string talentoH, string correo, string password, string nombre1, string nombre2, string apellido1, string apellido2, string fechaIngreso, string fechaCreacion, bool activo) {
            base.Channel.agregarUsuario(talentoH, correo, password, nombre1, nombre2, apellido1, apellido2, fechaIngreso, fechaCreacion, activo);
        }
        
        public System.Threading.Tasks.Task agregarUsuarioAsync(string talentoH, string correo, string password, string nombre1, string nombre2, string apellido1, string apellido2, string fechaIngreso, string fechaCreacion, bool activo) {
            return base.Channel.agregarUsuarioAsync(talentoH, correo, password, nombre1, nombre2, apellido1, apellido2, fechaIngreso, fechaCreacion, activo);
        }
        
        public GestionVacacionesUnitec.ServiceReference1.Usuario LogInUsuario(string email, string password) {
            return base.Channel.LogInUsuario(email, password);
        }
        
        public System.Threading.Tasks.Task<GestionVacacionesUnitec.ServiceReference1.Usuario> LogInUsuarioAsync(string email, string password) {
            return base.Channel.LogInUsuarioAsync(email, password);
        }
        
        public int LogIn2(string email, string password) {
            return base.Channel.LogIn2(email, password);
        }
        
        public System.Threading.Tasks.Task<int> LogIn2Async(string email, string password) {
            return base.Channel.LogIn2Async(email, password);
        }
        
        public void agregarDepartamento(string ID, string descripcion, bool activo) {
            base.Channel.agregarDepartamento(ID, descripcion, activo);
        }
        
        public System.Threading.Tasks.Task agregarDepartamentoAsync(string ID, string descripcion, bool activo) {
            return base.Channel.agregarDepartamentoAsync(ID, descripcion, activo);
        }
        
        public void agregarRol(string ID, string descripcion, bool activo) {
            base.Channel.agregarRol(ID, descripcion, activo);
        }
        
        public System.Threading.Tasks.Task agregarRolAsync(string ID, string descripcion, bool activo) {
            return base.Channel.agregarRolAsync(ID, descripcion, activo);
        }
        
        public void Rol_Permiso(string ID_rol, string ID_permiso) {
            base.Channel.Rol_Permiso(ID_rol, ID_permiso);
        }
        
        public System.Threading.Tasks.Task Rol_PermisoAsync(string ID_rol, string ID_permiso) {
            return base.Channel.Rol_PermisoAsync(ID_rol, ID_permiso);
        }
        
        public void Usuario_Departamento(string Talento_Humano, string descripcion_departamento) {
            base.Channel.Usuario_Departamento(Talento_Humano, descripcion_departamento);
        }
        
        public System.Threading.Tasks.Task Usuario_DepartamentoAsync(string Talento_Humano, string descripcion_departamento) {
            return base.Channel.Usuario_DepartamentoAsync(Talento_Humano, descripcion_departamento);
        }
        
        public void Usuario_Rol(string Talento_Humano, string descripcion_rol) {
            base.Channel.Usuario_Rol(Talento_Humano, descripcion_rol);
        }
        
        public System.Threading.Tasks.Task Usuario_RolAsync(string Talento_Humano, string descripcion_rol) {
            return base.Channel.Usuario_RolAsync(Talento_Humano, descripcion_rol);
        }
        
        public GestionVacacionesUnitec.ServiceReference1.tbl_usuarios LogInUsuario2(string email, string password) {
            return base.Channel.LogInUsuario2(email, password);
        }
        
        public System.Threading.Tasks.Task<GestionVacacionesUnitec.ServiceReference1.tbl_usuarios> LogInUsuario2Async(string email, string password) {
            return base.Channel.LogInUsuario2Async(email, password);
        }
        
        public GestionVacacionesUnitec.ServiceReference1.tbl_departamento[] ListaDeDepartamentos() {
            return base.Channel.ListaDeDepartamentos();
        }
        
        public System.Threading.Tasks.Task<GestionVacacionesUnitec.ServiceReference1.tbl_departamento[]> ListaDeDepartamentosAsync() {
            return base.Channel.ListaDeDepartamentosAsync();
        }
        
        public GestionVacacionesUnitec.ServiceReference1.tbl_roles[] ListaDeRoles() {
            return base.Channel.ListaDeRoles();
        }
        
        public System.Threading.Tasks.Task<GestionVacacionesUnitec.ServiceReference1.tbl_roles[]> ListaDeRolesAsync() {
            return base.Channel.ListaDeRolesAsync();
        }
        
        public GestionVacacionesUnitec.ServiceReference1.tbl_roles ListaDeRolesPorUsuario(string talento_humano) {
            return base.Channel.ListaDeRolesPorUsuario(talento_humano);
        }
        
        public System.Threading.Tasks.Task<GestionVacacionesUnitec.ServiceReference1.tbl_roles> ListaDeRolesPorUsuarioAsync(string talento_humano) {
            return base.Channel.ListaDeRolesPorUsuarioAsync(talento_humano);
        }
    }
}
